# Generated by Django 5.2.8 on 2025-12-01 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=10)),
                ('icone', models.CharField(choices=[('restaurant', 'Alimentação'), ('local_gas_station', 'Combustível'), ('directions_bus', 'Transporte'), ('home', 'Moradia'), ('shopping_cart', 'Compras'), ('medical_services', 'Saúde'), ('school', 'Educação'), ('sports_esports', 'Lazer'), ('checkroom', 'Vestuário'), ('work', 'Trabalho'), ('attach_money', 'Salário'), ('trending_up', 'Investimento'), ('card_giftcard', 'Presente'), ('more_horiz', 'Outros')], default='more_horiz', max_length=30)),
                ('cor', models.CharField(default='#6B7280', max_length=7)),
                ('padrao', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['tipo', 'nome'],
                'unique_together': {('usuario', 'nome', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa'), ('transferencia', 'Transferência')], max_length=15)),
                ('descricao', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data', models.DateField()),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes', to='transacoes.categoria')),
                ('conta_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacoes_entrada', to='contas.conta')),
                ('conta_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacoes_saida', to='contas.conta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'ordering': ['-data', '-created_at'],
                'indexes': [models.Index(fields=['usuario', '-data'], name='transacoes__usuario_b20f34_idx'), models.Index(fields=['tipo', 'data'], name='transacoes__tipo_6901e8_idx')],
            },
        ),
    ]
