# Generated by Django 5.2.8 on 2025-12-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('conta_corrente', 'Conta Corrente'), ('poupanca', 'Poupança'), ('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('investimento', 'Investimento'), ('outro', 'Outro')], max_length=20)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('icone', models.CharField(choices=[('wallet', 'Carteira'), ('credit_card', 'Cartão'), ('account_balance', 'Banco'), ('savings', 'Poupança'), ('trending_up', 'Investimento'), ('payments', 'Pagamento')], default='wallet', max_length=30)),
                ('cor', models.CharField(choices=[('#12A454', 'Verde'), ('#3B82F6', 'Azul'), ('#8B5CF6', 'Roxo'), ('#F59E0B', 'Laranja'), ('#EF4444', 'Vermelho'), ('#6B7280', 'Cinza')], default='#12A454', max_length=7)),
                ('ativa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
                'ordering': ['-ativa', 'nome'],
            },
        ),
    ]
