# Generated by Django 5.2.8 on 2025-12-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plano', models.CharField(choices=[('mensal', 'Mensal'), ('anual', 'Anual')], max_length=10)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('cancelada', 'Cancelada'), ('expirada', 'Expirada'), ('pendente', 'Pendente')], default='pendente', max_length=15)),
                ('purchase_token', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('product_id', models.CharField(blank=True, max_length=100)),
                ('order_id', models.CharField(blank=True, max_length=100)),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_expiracao', models.DateTimeField()),
                ('data_cancelamento', models.DateTimeField(blank=True, null=True)),
                ('renovacao_automatica', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LogPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log de Pagamento',
                'verbose_name_plural': 'Logs de Pagamento',
                'ordering': ['-created_at'],
            },
        ),
    ]
